// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGAoy6Ay6_I1YJpa9EIAPh4FFw7vByEE',
    appId: '1:1047519468398:web:4a8808ea10887798427f7f',
    messagingSenderId: '1047519468398',
    projectId: 'weatherapp-7568a',
    authDomain: 'weatherapp-7568a.firebaseapp.com',
    storageBucket: 'weatherapp-7568a.firebasestorage.app',
    measurementId: 'G-M5DKKPRMCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3H0mbcP3qJMnA2WRlPJqJTKBVEVSmHc',
    appId: '1:1047519468398:android:88d269ca76d12125427f7f',
    messagingSenderId: '1047519468398',
    projectId: 'weatherapp-7568a',
    storageBucket: 'weatherapp-7568a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv0y_dEAm9d90q5q6gRZ9-BIE24_R3M9U',
    appId: '1:1047519468398:ios:ab3a92a37a958d05427f7f',
    messagingSenderId: '1047519468398',
    projectId: 'weatherapp-7568a',
    storageBucket: 'weatherapp-7568a.firebasestorage.app',
    iosBundleId: 'com.example.trinhVanHao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv0y_dEAm9d90q5q6gRZ9-BIE24_R3M9U',
    appId: '1:1047519468398:ios:ab3a92a37a958d05427f7f',
    messagingSenderId: '1047519468398',
    projectId: 'weatherapp-7568a',
    storageBucket: 'weatherapp-7568a.firebasestorage.app',
    iosBundleId: 'com.example.trinhVanHao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvGAoy6Ay6_I1YJpa9EIAPh4FFw7vByEE',
    appId: '1:1047519468398:web:dde54a263a612759427f7f',
    messagingSenderId: '1047519468398',
    projectId: 'weatherapp-7568a',
    authDomain: 'weatherapp-7568a.firebaseapp.com',
    storageBucket: 'weatherapp-7568a.firebasestorage.app',
    measurementId: 'G-1BHB7LH3CD',
  );
}
